symbol_width = 16
symbol_height = 16

[symbols.Health]
x = 0
y = 0

[symbols.Speed]
x = 1
y = 0

[symbols.Engine]
x = 2
y = 0

[symbols.Tyres]
x = 3
y = 0

[symbols.Armour]
x = 4
y = 0

[symbols.Letter]
x = 5
y = 0
