sudo: required

language: rust

rust:
- stable
- beta
- nightly

os:
- osx
- linux

dist: trusty

before_install:
- "scripts/install.sh"

script:
- "scripts/build.sh"

deploy:
  skip_cleanup: true
  provider: s3
  region: ap-southeast-2
  access_key_id: AKIAJTZWT26OECTU2UVQ
  secret_access_key:
    secure: QXURikBASifE5zabgGtNvhSeasQq9f9HIXZ0mXGytoWBnDQW86CHEyvKpXbs4ySoSJemC1NhR6u3pcFTLw5NYRT1fM8BtXgQ4FVWSdrqUcyiBAFgoqR5xL92DXqu09YHHMDpZOp071HIK5RNWSIImHF4yZwPnr8HTDlUanSelLygCeq8rdQ4KFTpQaf5dIVNMvPMKzQvdLEgJCHKg1uIh81UXttWmICyM9SsMslct5eEejc9GiyFMAFE6uAGUbxyFfZIWMwQkGatp4pgLOAgAJ5qwBdmsPIeTWDvQKdqfZQBkBtFzNV8Cc6bjEfMrRyvz/shrk8KG06LxazDmsI7hYAZNYpZE7O82NAC/FkTVP4FyAbHnkZghIxahiADE/c0T11rJMNduYDIzBp1Fn/8qycQpW3hagXRvOfnI76pFzu+2YaUEdSNpOD4oBZUhcPtRcHmDMnYCYCdgpLsXKklRi9N6Ec9uqTXcttk58m9k79w9WglBICLzN+FSNmiYuBpBzd5+lkV7bOVlE3vs9oJjFL1f/C4bs1hxsoKV/aq1tTzxYKsfhPtikQGz/SrVnA3kfhh3fbx6cReD0coZZ0Zx6DJxPfW+ZH0sgm/pooAgdPC7VhQI92i5boojlY/79g+Gzk+FI9qnN4QJjPMHrimt8l6GOYMayAraAn6L1ZXyFA=
  bucket: gridbugs.org
  local-dir: uploads
  upload-dir: downloads
  acl: public_read
  on:
    all_branches: true
    repo: stevebob/apocalypse-post
    condition: $TRAVIS_RUST_VERSION = stable
