[package]
name = "howl"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
build = "build.rs"

[dependencies]
rand = "0.3.14"
num = "0.1.36"
itertools = "0.5.6"
getopts = "0.2.14"

[target.'cfg(unix)'.dependencies]
rustty = { git = "https://github.com/stevebob/rustty.git" }

[build-dependencies]
genecs = { git = "https://github.com/stevebob/genecs.git" }
