[package]
name = "howl"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
build = "build.rs"

[features]
default = ["sdl2", "rustty"]
use_sdl2_mac_framework = ["sdl2/use_mac_framework"]

[dependencies]
rand = "0.3.14"
num = "0.1.36"
itertools = "0.5.6"
getopts = "0.2.14"
toml = "0.2.1"
rustc-serialize = "0.3.19"
serde = "0.9.7"
serde_derive = "0.9.7"
bincode = "1.0.0-alpha2"

[dependencies.sdl2]
version = "0.28.0"
optional = true
default-features = false
features = ["image", "ttf"]

[target.'cfg(unix)'.dependencies]
rustty = { git = "https://github.com/stevebob/rustty.git", optional = true }

[build-dependencies]
copy_dir = "0.1.2"
handlebars = "0.22.0"
tomson = "0.1.1"
rustc-serialize = "0.3.19"
genecs = { git = "https://github.com/stevebob/genecs.git", rev = "f307bba" }
