imports = [
    "coord::Coord",
    "game::*",
    "game::data::*",
    "util::ScheduleTicket",
    "direction::Direction",
]

[component.solid]
[component.collider]
[component.destroy_on_collision]
[component.pc]
[component.floor]
[component.should_render]
[component.enemy]
[component.projectile]
[component.projectile_collider]
[component.bump_attackable]
[component.acid_animation]

[component.can_run_over]
[component.can_be_run_over]
[component.bloodstain_on_death]
[component.destroy_when_stopped]

[component.bank]
    type = "usize"
    copy = true

[component.price]
    type = "usize"
    copy = true

[component.gun_type]
    type = "GunType"
    copy = true

[component.weapon_slots]
    type = "DirectionTable<EntityId>"
    container = "RefCell"

[component.current_speed]
    type = "usize"
    copy = true

[component.max_speed]
    type = "usize"
    copy = true

[component.redline_speed]
    type = "usize"
    copy = true

[component.num_tires]
    type = "usize"
    copy = true

[component.max_tires]
    type = "usize"
    copy = true

[component.facing]
    type = "Direction"
    copy = true

[component.bump_attacker]
    type = "usize"
    copy = true

[component.projectile_damage]
    type = "usize"
    copy = true

[component.hit_points]
    type = "HitPoints"
    copy = true

[component.realtime_velocity]
    type = "RealtimeVelocity"

[component.realtime_moves_remaining]
    type = "usize"
    copy = true

[component.tile]
    type = "TileType"
    copy = true

[component.position]
    type = "Coord"
    copy = true

[component.opacity]
    type = "f64"
    copy = true

[component.vision_distance]
    type = "usize"
    copy = true

[component.control_map]
    type = "ControlMap"
    container = "RefCell"

[component.tile_depth]
    type = "isize"
    copy = true

[component.message_log]
    type = "MessageLog"
    container = "RefCell"

[component.name]
    type = "NameMessageType"
    copy = true

[component.description]
    type = "DescriptionMessageType"
    copy = true

[component.behaviour_type]
    type = "BehaviourType"
    copy = true

[component.behaviour_state]
    type = "BehaviourState"
    container = "RefCell"

[component.turn_offset]
    type = "u64"
    copy = true

[component.drawable_knowledge]
    type = "DrawableKnowledge"
    container = "RefCell"

[component.simple_npc_knowledge]
    type = "SimpleNpcKnowledge"
    container = "RefCell"

[component.path_traverse]
    type = "PathTraverse"
    container = "RefCell"

[component.turn_time]
    type = "u64"
    copy = true

[component.shadow_entity]
    type = "EntityId"
    copy = true

[component.schedule_ticket]
    type = "ScheduleTicket"
    copy = true

[component.level_switch]
    type = "LevelSwitch"
    copy = true

[component.level_switch_auto]
[component.level_switch_group]
    type = "usize"
    copy = true

[component.probabilistic_animation]
    type = "FirstWeightedProbabilisticChoice<TileType>"

[component.inventory]
    type = "EntitySet"
    container = "RefCell"

[component.inventory_capacity]
    type = "usize"
    copy = true

[action_property.alternative_turn_time]
    type = "u64"
    copy = true

[action_property.action_time_ms]
    type = "u64"
    copy = true

[action_property.action_description]
    type = "ActionDescription"

[action_property.level_switch_action]
    type = "LevelSwitchAction"
    copy = true

[action_property.try_level_switch]
    type = "EntityId"
    copy = true

[action_property.projectile_collision]
    type = "ProjectileCollision"
    copy = true

[action_property.schedule_invalidate]
    type = "ScheduleTicket"
    copy = true

[action_property.no_commit]
[action_property.player_died]
[action_property.physics]
[action_property.steer]
[action_property.realtime_delay]
[action_property.start_realtime_move]
[action_property.then]
    type = "Reaction"
    copy = true
