imports = [
    "coord::Coord",
    "game::*",
    "game::data::*",
    "util::ScheduleTicket",
]

[component.solid]
[component.collider]
[component.door_opener]
[component.destroy_on_collision]
[component.pc]
[component.outside]
[component.moon]
[component.transform_on_moon_change]
[component.should_render]
[component.enemy]

[component.realtime_velocity]
    type = "RealtimeVelocity"

[component.tile]
    type = "TileType"
    copy = true

[component.position]
    type = "Coord"
    copy = true

[component.opacity]
    type = "f64"
    copy = true

[component.door_state]
    type = "DoorState"
    copy = true

[component.vision_distance]
    type = "usize"
    copy = true

[component.control_map]
    type = "ControlMap"

[component.tile_depth]
    type = "isize"
    copy = true

[component.message_log]
    type = "MessageLog"
    container = "RefCell"

[component.behaviour_type]
    type = "BehaviourType"
    copy = true

[component.behaviour_state]
    type = "BehaviourState"
    container = "RefCell"

[component.drawable_knowledge]
    type = "DrawableKnowledge"
    container = "RefCell"

[component.simple_npc_knowledge]
    type = "SimpleNpcKnowledge"
    container = "RefCell"

[component.path_traverse]
    type = "PathTraverse"
    container = "RefCell"

[component.turn_time]
    type = "u64"
    copy = true

[component.cloud_state]
    type = "CloudState"
    container = "RefCell"

[component.shadow_entity]
    type = "EntityId"
    copy = true

[component.transformation_state]
    type = "TransformationState"
    copy = true

[component.transformation_type]
    type = "TransformationType"
    copy = true

[component.schedule_ticket]
    type = "ScheduleTicket"

[action_property.alternative_turn_time]
    type = "u64"
    copy = true

[action_property.action_time_ms]
    type = "u64"
    copy = true

[action_property.close]
    type = "Close"

[action_property.action_description]
    type = "ActionDescription"
