imports = [
    "math::Coord",
    "frontends::ansi::ComplexTile",
    "game::*",
]

[component.solid]
[component.collider]
[component.door_opener]


[component.position]
    type = "Coord"
    copy = true

[component.opacity]
    type = "f64"
    copy = true

[component.door_state]
    type = "data::DoorState"
    copy = true

[component.vision_distance]
    type = "usize"
    copy = true

[component.ansi_tile]
    type = "ComplexTile"
    copy = true

[component.tile_depth]
    type = "isize"
    copy = true

[component.behaviour_type]
    type = "BehaviourType"
    copy = true

[component.behaviour_state]
    type = "BehaviourState"
    container = "RefCell"

[component.ansi_drawable_knowledge]
    type = "AnsiDrawableKnowledge"
    container = "RefCell"

[action_property.turn_time]
    type = "u64"
    copy = true

[action_property.action_time]
    type = "u64"
    copy = true
