imports = [
    "coord::Coord",
    "game::*",
    "game::data::*",
    "util::ScheduleTicket",
]

[component.solid]
[component.collider]
[component.door_opener]
[component.destroy_on_collision]
[component.pc]
[component.outside]
[component.moon]
[component.transform_on_moon_change]
[component.should_render]
[component.enemy]
[component.projectile]
[component.projectile_collider]
[component.bump_attackable]

[component.bump_attacker]
    type = "usize"
    copy = true

[component.projectile_damage]
    type = "usize"
    copy = true

[component.hit_points]
    type = "HitPoints"
    copy = true

[component.realtime_velocity]
    type = "RealtimeVelocity"

[component.tile]
    type = "TileType"
    copy = true

[component.position]
    type = "Coord"
    copy = true

[component.opacity]
    type = "f64"
    copy = true

[component.door_state]
    type = "DoorState"
    copy = true

[component.vision_distance]
    type = "usize"
    copy = true

[component.control_map]
    type = "ControlMap"
    container = "RefCell"

[component.tile_depth]
    type = "isize"
    copy = true

[component.message_log]
    type = "MessageLog"
    container = "RefCell"

[component.you_see]
    type = "YouSeeMessageType"
    copy = true

[component.description]
    type = "DescriptionMessageType"
    copy = true

[component.behaviour_type]
    type = "BehaviourType"
    copy = true

[component.behaviour_state]
    type = "BehaviourState"
    container = "RefCell"

[component.drawable_knowledge]
    type = "DrawableKnowledge"
    container = "RefCell"

[component.simple_npc_knowledge]
    type = "SimpleNpcKnowledge"
    container = "RefCell"

[component.path_traverse]
    type = "PathTraverse"
    container = "RefCell"

[component.turn_time]
    type = "u64"
    copy = true

[component.cloud_state]
    type = "CloudState"
    container = "RefCell"

[component.shadow_entity]
    type = "EntityId"
    copy = true

[component.transformation_state]
    type = "TransformationState"
    copy = true

[component.transformation_type]
    type = "TransformationType"
    copy = true

[component.schedule_ticket]
    type = "ScheduleTicket"
    copy = true

[component.level_switch_trigger]
    type = "LevelSwitch"
    copy = true

[component.level_switch_returnable]
[component.level_switch_auto]
[component.level_switch_group]
    type = "usize"
    copy = true

[action_property.alternative_turn_time]
    type = "u64"
    copy = true

[action_property.action_time_ms]
    type = "u64"
    copy = true

[action_property.close]
    type = "Close"

[action_property.action_description]
    type = "ActionDescription"

[action_property.level_switch_action]
    type = "LevelSwitchAction"
    copy = true

[action_property.try_level_switch]
    type = "EntityId"
    copy = true

[action_property.projectile_collision]
    type = "ProjectileCollision"
    copy = true

[action_property.schedule_invalidate]
    type = "ScheduleTicket"
    copy = true

[action_property.no_commit]
[action_property.player_died]
