[field.opacity]
    type = "sum_f64"

[field.solid]
    type = "count_bool"

[field.pc]
    type = "count_bool"

[field.enemy]
    type = "any"

[field.level_switch]
    type = "any"
    component_has_type = true

[field.floor]
    type = "any"

[field.bump_attackable]
    type = "any"

[field.transformation_state]
    type = "set"
    component_has_type = true

[field.projectile_collider]
    type = "any"

[field.hit_points]
    type = "void"
    component_has_type = true

[field.tile]
    type = "void"
    component_has_type = true
