[field.opacity]
    type = "sum_f64"

[field.solid]
    type = "any"

[field.pc]
    type = "count_bool"

[field.acid]
    type = "count_bool"

[field.letter]
    type = "any"

[field.enemy]
    type = "any"

[field.level_switch]
    type = "any"
    component_has_type = true

[field.floor]
    type = "any"

[field.bump_attackable]
    type = "any"

[field.projectile_collider]
    type = "any"

[field.hit_points]
    type = "void"
    component_has_type = true

[field.tile]
    type = "void"
    component_has_type = true

[field.destroyed_by_explosion]
    type = "set"
