tile_width = 16
tile_height = 16
tile_padding = 0

[extra]
Blank = { x = 16, y = 0 }
Moon = { x = 13, y = 0 }
AimLine = { x = 14, y = 0 }
Death = { x = 17, y = 0 }

[tiles.Player]
foreground = { x = 0, y = 0 }

[tiles.TerrorPillar]
foreground = { x = 1, y = 0 }

[tiles.TerrorFly]
foreground = { x = 2, y = 0 }

[tiles.Tree]
foreground = { x = 3, y = 0 }

[tiles.DeadTree]
foreground = { x = 4, y = 0 }

[tiles.Floor]
background = { x = 7, y = 0 }
foreground = { x = 5, y = 0 }

[tiles.Ground]
background = { x = 7, y = 0 }
foreground = { x = 6, y = 0 }

[tiles.Wall.front]
background = { x = 8, y = 0 }

[tiles.Wall.back]
background = { x = 9, y = 0 }

[tiles.ClosedDoor]
background = { x = 10, y = 0 }

[tiles.OpenDoor]
foreground = { x = 11, y = 0 }

[tiles.Bullet]
foreground = { x = 12, y = 0 }

[tiles.Book]
foreground = { x = 15, y = 0 }

[tiles.DownStairs]
foreground = { x = 18, y = 0 }

[tiles.UpStairs]
foreground = { x = 19, y = 0 }
