tile_width = 16
tile_height = 16
tile_padding = 0

[extra]
Death = { x = 0, y = 4 }
Blank = { x = 0, y = 5 }

[tiles.Van]
foreground = { x = 1, y = 0 }

[tiles.Zombie]
foreground = { x = 0, y = 0 }

[tiles.Wreck0]
foreground = { x = 2, y = 0 }

[tiles.Wreck1]
foreground = { x = 3, y = 0 }

[tiles.Wreck2]
foreground = { x = 4, y = 0 }

[tiles.Bullet]
foreground = { x = 5, y = 0 }

[tiles.Bloodstain]
foreground = { x = 6, y = 0 }

[tiles.Road0]
background = { x = 0, y = 1 }
foreground = { x = 1, y = 1 }

[tiles.Dirt0]
background = { x = 0, y = 2 }
foreground = { x = 1, y = 2 }

[tiles.Dirt1]
background = { x = 0, y = 2 }
foreground = { x = 2, y = 2 }

[tiles.Acid0]
background = { x = 0, y = 3 }
foreground = { x = 1, y = 3 }

[tiles.Acid1]
background = { x = 0, y = 3 }
foreground = { x = 2, y = 3 }

[tiles.RailgunSlugVertical]
foreground = { x = 7, y = 0 }

[tiles.RailgunSlugHorizontal]
foreground = { x = 8, y = 0 }
